services:
  - type: web
    name: betinha
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build && npm run db:push && npx tsx script/seed.ts
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
